### ISSUE TITLE
Licensing Installer 1.0 Fehlercode: 131372 Exit Status: 2 *solved*

### ISSUE THREAD

**Issue by hinataluna** [cryinkfly/Autodesk-Revit-for-Linux#1]
Hello, thanks for your project.
I'd love to be able to use Revit on my Linux machine.

However, I see you didn't complete your writeup yet... is it still a thing?
Thank you :)

**Comment by cryinkfly** [comment]
Hey, the installation is currently crashing with error 1603 or 131372 at around 16%.

There are still a few dependencies that I have to solve. :+1:

**Comment by cryinkfly** [comment]
The same problem is when I will install AutoCAD 2022!

Here I found a solution for windows system: https://knowledge.autodesk.com/de/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/DEU/Install-failed-when-installing-Autodesk-software-and-the-Install-log-indicates-Autodesk-Licensing-Installer-1-0-Error-Code-131372-Exit-Status-2.html

**Comment by cryinkfly** [comment]
I have solved this issue with the help of winetricks!

sh winetricks cmd

But I get the next error: Autodesk Licensing Installer 1.0 Fehlercode: 250 Exit Status: 2
